"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { AlertTriangle,ArrowRight,Check,CheckCircle2,Clock3,Factory,FlaskConical,Link2,PackageCheck,QrCode,ScanLine,Store,Truck,Wallet,XCircle } from "lucide-react";
import { createPublicClient,createWalletClient,custom,http,keccak256,stringToHex,type Address,type Hash } from "viem";
import { baseSepolia,contractAbi,type BatchView } from "../lib/contract";
declare global{interface Window{ethereum?:{request(args:{method:string;params?:unknown[]}):Promise<unknown>}}}
type ChainData={batch:BatchView;history:Array<{id:string;fromAddress:string;toAddress:string;timestamp:number;evidenceHash:string}>;forkAttempts:Array<{id:number;txHash:string;actor:string;reason:string;createdAt:number}>};
type Config={contractAddress:Address|null;chainId:number;chainName:string;explorer:string};
type TxFn=(f:"registerBatch"|"initiateTransfer"|"acceptTransfer"|"markDispensed",a:readonly unknown[])=>Promise<Hash>;
const short=(v:string)=>`${v.slice(0,6)}…${v.slice(-4)}`;
const date=(v:number)=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v*1000));
const parseId=(raw:string)=>{const v=raw.trim();try{const p=JSON.parse(v);if(p.batchId)return String(p.batchId);}catch{}return v.match(/(?:batch\/|batchId=)?(\d+)$/)?.[1]||v};

export default function Home(){
 const [tab,setTab]=useState<"verify"|"portal">("verify"),[config,setConfig]=useState<Config|null>(null),[input,setInput]=useState(""),[chain,setChain]=useState<ChainData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[account,setAccount]=useState<Address|null>(null),[notice,setNotice]=useState(""),[batches,setBatches]=useState<BatchView[]>([]);const qrRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch("/api/config").then(async r=>setConfig(await r.json() as Config)).catch(()=>setError("Registry configuration is unavailable."))},[]);
 useEffect(()=>{fetch("/api/batches").then(async r=>r.ok?await r.json() as {batches:BatchView[]}:null).then(v=>v&&setBatches(v.batches||[])).catch(()=>{})},[notice]);
 const mine=useMemo(()=>batches.filter(b=>account&&b.manufacturer.toLowerCase()===account.toLowerCase()),[batches,account]);
 async function verify(raw=input){setError("");setChain(null);const id=parseId(raw);if(!/^\d+$/.test(id)){setError("Enter the numeric batch ID or scan a RantaiObat QR code.");return}setLoading(true);try{const r=await fetch(`/api/batches/${id}/chain`),d=await r.json() as ChainData&{error?:string};if(!r.ok)throw new Error(d.error||"Unable to verify this batch.");setChain(d);setInput(id)}catch(e){setError(e instanceof Error?e.message:"Unable to verify this batch.")}finally{setLoading(false)}}
 async function connect(){if(!window.ethereum){setError("Install a browser wallet such as MetaMask to use the custody portal.");return}try{const a=await window.ethereum.request({method:"eth_requestAccounts"}) as Address[];setAccount(a[0]);setError("")}catch{setError("Wallet connection was cancelled.")}}
 const transact:TxFn=async(functionName,args)=>{if(!account||!config?.contractAddress||!window.ethereum)throw new Error("Connect a wallet and configure the contract first.");const wallet=createWalletClient({account,chain:baseSepolia,transport:custom(window.ethereum)});try{await wallet.switchChain({id:baseSepolia.id})}catch{await wallet.addChain({chain:baseSepolia})}const hash=await wallet.writeContract({address:config.contractAddress,abi:contractAbi,functionName,args,gas:500000n} as never);const receipt=await createPublicClient({chain:baseSepolia,transport:http()}).waitForTransactionReceipt({hash});if(receipt.status!=="success"){if(functionName==="initiateTransfer")await fetch("/api/fork-attempts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({txHash:hash,batchId:String(args[0])})}).catch(()=>{});throw new Error("The contract rejected this transaction. A genuine non-holder fork attempt is recorded after chain verification.")}return hash};
 async function scan(){if(!qrRef.current)return;setError("");try{const{Html5Qrcode}=await import("html5-qrcode");const scanner=new Html5Qrcode("qr-reader");await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:240,height:240}},async decoded=>{await scanner.stop();setInput(decoded);verify(decoded)},()=>{})}catch(e){setError(e instanceof Error?e.message:"Camera access is unavailable. Paste the batch ID instead.")}}
 const status=chain?.forkAttempts.length?"Broken chain attempt":chain?.batch.status==="Flagged"?"Flagged":chain?.batch.status==="Recalled"?"Recalled":"Verified";
 return <main className="min-h-screen"><header className="topbar"><a className="brand" href="#"><span className="brandmark"><Link2/></span><span>RantaiObat<small>Medicine Chain</small></span></a><nav><button className={tab==="verify"?"active":""} onClick={()=>setTab("verify")}>Verify medicine</button><button className={tab==="portal"?"active":""} onClick={()=>setTab("portal")}>Custody portal</button></nav><button className="wallet" onClick={connect}><Wallet size={17}/>{account?short(account):"Connect wallet"}</button></header>
 {tab==="verify"?<><section className="verify-hero"><div className="eyebrow"><span>PUBLIC CHECK</span> BASE SEPOLIA · NO SIGN-IN</div><h1>Trace this batch.<span>Before it reaches a patient.</span></h1><p>Read the custody record written by manufacturers, distributors, and pharmacies. A handoff appears only after both organizations sign.</p><div className="search"><div className="search-label"><ScanLine/><span><b>Batch lookup</b><small>Numeric ID or QR payload</small></span></div><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&verify()} placeholder="Example: 1842"/><button onClick={()=>verify()} disabled={loading}>{loading?"Checking ledger…":"Check custody"}</button><button className="scan" onClick={scan} aria-label="Scan QR"><QrCode/><span>Scan QR</span></button></div><div id="qr-reader" ref={qrRef}/>{!config?.contractAddress&&<div className="setup-note"><Clock3/> Testnet contract has not been connected to this deployment yet.</div>}</section>{error&&<div className="alert error"><XCircle/>{error}</div>}{chain&&<Result chain={chain} status={status} config={config}/>} {!chain&&!error&&<section className="proof-line"><div><small>WHY THE RECORD HOLDS</small><strong>Custody changes by agreement, not by assertion.</strong></div><ol><li><b>01</b><span>Current holder proposes</span></li><li><b>02</b><span>Recipient co-signs</span></li><li><b>03</b><span>Contract changes custody</span></li><li><b>04</b><span>Anyone can verify</span></li></ol></section>}</>:<Portal account={account} connect={connect} config={config} myBatches={mine} allBatches={batches} transact={transact} setNotice={setNotice} notice={notice}/>}<footer><span>RantaiObat</span><p>Custody lives on-chain. The database only indexes verified evidence.</p><a href="https://sepolia.basescan.org" target="_blank">Inspect Base Sepolia ↗</a></footer></main>
}
function Result({chain,status,config}:{chain:ChainData;status:string;config:Config|null}){return <section className="result-shell"><div className={`verdict ${status.toLowerCase().replaceAll(" ","-")}`}><div>{status==="Verified"?<CheckCircle2/>:<AlertTriangle/>}<span><small>CHAIN STATUS</small><strong>{status}</strong></span></div><p>{status==="Verified"?"All recorded custody handoffs are complete and cryptographically signed.":"This batch has a regulator flag, recall, or a verified rejected fork attempt."}</p><a href={`${config?.explorer}/address/${config?.contractAddress}`} target="_blank">View contract <ArrowRight/></a></div><div className="batch-grid"><article className="medicine-card"><div className="pill-icon"><FlaskConical/></div><div><small>MEDICINE</small><h2>{chain.batch.drugName}</h2><p>Batch <b>{chain.batch.batchCode}</b></p></div><dl><div><dt>Produced</dt><dd>{date(chain.batch.productionDate)}</dd></div><div><dt>Expires</dt><dd>{date(chain.batch.expiryDate)}</dd></div><div><dt>On-chain ID</dt><dd>#{chain.batch.id}</dd></div><div><dt>State</dt><dd>{chain.batch.dispensed?"Dispensed":chain.batch.status}</dd></div></dl></article><article className="custody"><div className="section-title"><div><small>IMMUTABLE AUDIT TRAIL</small><h2>Custody timeline</h2></div><span>{chain.history.length+1} attestations</span></div><Timeline chain={chain}/></article></div></section>}
function Timeline({chain}:{chain:ChainData}){const rows=[{id:"origin",fromAddress:"",toAddress:chain.batch.manufacturer,timestamp:chain.batch.productionDate,evidenceHash:"Founding manufacturer attestation"},...chain.history];return <div className="timeline">{rows.map((t,i)=><div className="timeline-row" key={t.id}><span className="dot">{i===0?<Factory/>:i===rows.length-1?<Store/>:<Truck/>}</span><div><small>{i===0?"REGISTERED":`TRANSFER ${i}`}</small><h3>{i===0?"Manufactured and registered":`${short(t.fromAddress)} → ${short(t.toAddress)}`}</h3><p>{date(t.timestamp)} · {i===0?short(t.toAddress):"Both parties signed"}</p>{i>0&&<code>{short(t.evidenceHash)}</code>}</div><Check/></div>)}{chain.forkAttempts.map(a=><div className="timeline-row danger" key={`f-${a.id}`}><span className="dot"><XCircle/></span><div><small>COUNTERFEITING ATTEMPT DETECTED</small><h3>Rejected fork by {short(a.actor)}</h3><p>{a.reason}</p><code>{short(a.txHash)}</code></div><AlertTriangle/></div>)}</div>}
function Portal({account,connect,config,myBatches,allBatches,transact,setNotice,notice}:{account:Address|null;connect:()=>void;config:Config|null;myBatches:BatchView[];allBatches:BatchView[];transact:TxFn;setNotice:(s:string)=>void;notice:string}){const[busy,setBusy]=useState(false),[err,setErr]=useState("");async function run(label:string,fn:()=>Promise<Hash>){setBusy(true);setErr("");setNotice("");try{const h=await fn();setNotice(`${label} confirmed: ${short(h)}`)}catch(e){setErr(e instanceof Error?e.message:"Transaction failed")}finally{setBusy(false)}}if(!account)return <section className="gate"><span><Wallet/></span><small>CUSTODY PORTAL</small><h1>Sign in with your wallet</h1><p>Your wallet signature identifies the organization taking responsibility for each batch. No password or private key is sent to RantaiObat.</p><button onClick={connect}>Connect wallet <ArrowRight/></button></section>;return <section className="portal"><div className="portal-head"><div><small>CONNECTED AS {short(account)}</small><h1>Custody operations</h1><p>Every action below writes directly to the Base Sepolia contract.</p></div><span className="network"><i/> Base Sepolia</span></div>{!config?.contractAddress&&<div className="alert error"><AlertTriangle/> Deploy the contract and set CONTRACT_ADDRESS before submitting transactions.</div>}{notice&&<div className="alert success"><CheckCircle2/>{notice}</div>}{err&&<div className="alert error"><XCircle/>{err}</div>}<div className="operation-grid"><RegisterCard disabled={busy||!config?.contractAddress} run={run} transact={transact}/><TransferCard disabled={busy||!config?.contractAddress} batches={allBatches.filter(b=>b.currentHolder.toLowerCase()===account.toLowerCase()&&!b.dispensed&&b.status==="Active")} run={run} transact={transact}/><AcceptCard disabled={busy||!config?.contractAddress} run={run} transact={transact}/></div><div className="holdings"><div className="section-title"><div><small>MANUFACTURER RECORDS</small><h2>Your registered batches</h2></div><span>{myBatches.length}</span></div>{myBatches.length?myBatches.map(b=><div className="holding" key={b.id}><PackageCheck/><div><b>{b.drugName}</b><small>{b.batchCode} · ID #{b.id}</small></div><span>{b.status}</span></div>):<p className="empty">No batches registered by this wallet yet.</p>}</div></section>}
function RegisterCard({disabled,run,transact}:{disabled:boolean;run:any;transact:TxFn}){const[d,setD]=useState(""),[c,setC]=useState(""),[p,setP]=useState(""),[x,setX]=useState("");return <form className="op-card" onSubmit={e=>{e.preventDefault();run("Batch registration",()=>transact("registerBatch",[d,c,BigInt(new Date(p).getTime()/1000),BigInt(new Date(x).getTime()/1000)]))}}><Title icon={<Factory/>} step="01" title="Register batch"/><label>Medicine name<input required value={d} onChange={e=>setD(e.target.value)} placeholder="Amoxicillin 500mg"/></label><label>Batch code<input required value={c} onChange={e=>setC(e.target.value)} placeholder="AMX-260920-A"/></label><div className="split"><label>Produced<input required type="date" value={p} onChange={e=>setP(e.target.value)}/></label><label>Expires<input required type="date" value={x} onChange={e=>setX(e.target.value)}/></label></div><button disabled={disabled}>Sign & register</button></form>}
function TransferCard({disabled,batches,run,transact}:{disabled:boolean;batches:BatchView[];run:any;transact:TxFn}){const[id,setId]=useState(""),[to,setTo]=useState(""),[ev,setEv]=useState("");return <form className="op-card" onSubmit={e=>{e.preventDefault();run("Transfer initiation",()=>transact("initiateTransfer",[BigInt(id),to as Address,keccak256(stringToHex(ev))]))}}><Title icon={<Truck/>} step="02" title="Initiate handoff"/><label>Batch<select required value={id} onChange={e=>setId(e.target.value)}><option value="">Select batch</option>{batches.map(b=><option value={b.id} key={b.id}>#{b.id} · {b.batchCode}</option>)}</select></label><label>Recipient wallet<input required value={to} onChange={e=>setTo(e.target.value)} placeholder="0x…"/></label><label>Manifest reference<input required value={ev} onChange={e=>setEv(e.target.value)} placeholder="IPFS CID or manifest number"/></label><button disabled={disabled}>Sign handoff</button></form>}
function AcceptCard({disabled,run,transact}:{disabled:boolean;run:any;transact:TxFn}){const[t,setT]=useState(""),[b,setB]=useState("");return <div className="op-card"><Title icon={<PackageCheck/>} step="03" title="Receive or dispense"/><form onSubmit={e=>{e.preventDefault();run("Transfer acceptance",()=>transact("acceptTransfer",[BigInt(t)]))}}><label>Incoming transfer ID<input required value={t} onChange={e=>setT(e.target.value)} placeholder="Transfer ID"/></label><button disabled={disabled}>Co-sign acceptance</button></form><div className="or">OR</div><form onSubmit={e=>{e.preventDefault();run("Dispensing",()=>transact("markDispensed",[BigInt(b)]))}}><label>Batch ID<input required value={b} onChange={e=>setB(e.target.value)} placeholder="Batch held by this wallet"/></label><button className="secondary" disabled={disabled}>Mark dispensed</button></form></div>}
function Title({icon,step,title}:{icon:React.ReactNode;step:string;title:string}){return <div className="icon-title"><span>{icon}</span><div><small>STEP {step}</small><h2>{title}</h2></div></div>}
